apiVersion: config.eda.nokia.com/v1alpha1
kind: Configlet
metadata:
  name: jsonrpc
  namespace: eda-telemetry
spec:
  configs:
    - path: .system.json-rpc-server
      operation: Create
      config: |-
        {
            "admin-state": "enable",
            "network-instance": [
              {
                "name": "mgmt",
                "http": {
                  "admin-state": "enable"
                }
              }
            ]
        }
  endpointSelector:
    - eda.nokia.com/role=leaf
    - eda.nokia.com/role=spine
  operatingSystem: srl
